test correct deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,8 +32,8 @@ jobs:
           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
           SSH_IP: ${{ secrets.SSH_IP }}
 
-      - name: Intentionally fail deployment
-        run: exit 1
+      # - name: Intentionally fail deployment
+      #   run: exit 1
 
       - name: Deploy site
         run: ssh my-vps '~/redeploy-site.sh'
